######################################################################
# Automatically generated by qmake (2.01a) ?r kw 25 16:45:16 2007
######################################################################

TEMPLATE = app
TARGET = kshutdown
DEPENDPATH += .
INCLUDEPATH += .

# KShutDown:
DEFINES += KS_PURE_QT
unix {
	CONFIG += qdbus
}

# Input
HEADERS += kshutdown.h mainwindow.h pureqt.h version.h
SOURCES += kshutdown.cpp main.cpp mainwindow.cpp
