// Generated by ./tools/make-version.sh, do not modify!
#ifndef KSHUTDOWN_VERSION_H
#define KSHUTDOWN_VERSION_H

#define KS_BUILD "20110215"
#define KS_FILE_VERSION "2.0beta12"
#define KS_FULL_VERSION "2.0 Beta 12"

#endif // KSHUTDOWN_VERSION_H
