// Generated by ./tools/make-version.sh, do not modify!
#ifndef KSHUTDOWN_VERSION_H
#define KSHUTDOWN_VERSION_H

#include <QtGlobal>

#define KS_APP_VERSION "5.0"
#define KS_RELEASE_DATE "2019-05-06"

#if QT_VERSION < 0x050900
	#error "KShutdown 5.0 requires Qt 5.9 or newer"
#endif // QT_VERSION

#if defined(KS_KF5) && defined(KS_PURE_QT)
	#error "Please use only one -DKS_KF5 or -DKS_PURE_QT compiler option"
#endif

#if !defined(KS_KF5) && !defined(KS_PURE_QT)
	#error "Please use either -DKS_KF5 or -DKS_PURE_QT compiler option (see Setup*.sh)"
#endif

#ifdef KS_NATIVE_KDE
	#error "Please use KS_KF5 instead of KS_NATIVE_KDE"
#endif // KS_NATIVE_KDE

#endif // KSHUTDOWN_VERSION_H
