// Generated by ./tools/make-version.sh, do not modify!
#ifndef KSHUTDOWN_VERSION_H
#define KSHUTDOWN_VERSION_H

#define KS_BUILD "20120301"
#define KS_FILE_VERSION "3.0beta3"
#define KS_FULL_VERSION "3.0 Beta 3"

#endif // KSHUTDOWN_VERSION_H
