#!/bin/bash

KS_BUILD=`date +%Y%m%d`
KS_VERSION=`cat tools/VERSION`

echo "// Generated by $0, do not modify!">"src/version.h"
echo "#define KS_BUILD \"$KS_BUILD\"">>"src/version.h"
echo "#define KS_VERSION \"$KS_VERSION\"">>"src/version.h"
