// Generated by ./tools/make-version.sh, do not modify!
#ifndef KSHUTDOWN_VERSION_H
#define KSHUTDOWN_VERSION_H

#define KS_BUILD "2016-04-29"
#define KS_FILE_VERSION "3.99.1beta"
#define KS_FULL_VERSION "3.99.1 Beta"

#endif // KSHUTDOWN_VERSION_H
